#!/usr/bin/env bash
# a bash script that displays info about subdomains
# domain zone is configured so that the subdomain www,
# points to the load-balancer IP(lb-01).

dns_configuration () {
    link=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1)
    echo "$2 $link" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ "$#" == 1 ]
then
  dns_configuration "$1" "www"
  dns_configuration "$1" "lb-01"
  dns_configuration "$1" "web-01"
  dns_configuration "$1" "web-02"
elif [ "$#" == 2 ]
then
  dns_configuration "$1" "$2"
fi
